### PR TITLE
Update bruteforce_attack_timer.py

### PR DESCRIPTION
**Pull request by MDA1422**

### CODE REVIEW

**Comment by grugnoymeme** [comment]
I would like that the two scripts is indipendent by each other. So i would not import `bruteforce_attack.py` in the timer version. Doing like u suggest, if i delete the `bruteforce_attack.py` version, the "timer" one is not working alone..

**Comment by MDA1422** [comment]
no need to delete, just thought that some lines of code could be shorten with a few functions, but your work is perfect as it is

**Comment by grugnoymeme** [comment]
Yes!! In fact i like just half of your pull request!! The half that close the lines in a function. I just think that is good to have 2 separate script. You understand? If you want open a pull request with just the half that i told you and i'll merge it!! 😃 thank u!!

**Comment by grugnoymeme** [comment]
Yes it could be great but u understand why id like to keep that separate??? 😃 anyway im working to the GUI version, at now i made just the dictionary way.. but we can work together on the bruteforce one 😃 if u like obviously.. thanks a lot!!

**Pull request closed without merging**
